<a href="https://colab.research.google.com/github/Saroj-lab/Assessment1/blob/main/PreprocessingCasteStudy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [144]:
import numpy as np
import pandas as pd

In [145]:
df = pd.read_csv('/content/House_Pricing.csv')
df

,ID,Date House was Sold,Sale Price,No of Bedrooms,No of Bathrooms,Flat Area (in Sqft),Lot Area (in Sqft),No of Floors,Waterfront View,No of Times Visited,...,Overall Grade,Area of the House from Basement (in Sqft),Basement Area (in Sqft),Age of House (in Years),Renovated Year,Zipcode,Latitude,Longitude,Living Area after Renovation (in Sqft),Lot Area after Renovation (in Sqft)
0,7129300520,14 October 2017,221900.0,3,1.00,1180.0,5650.0,1.0,No,NaN,...,7,1180.0,0,63,0,98178.0,47.5112,-122.257,1340.0,5650
1,6414100192,14 December 2017,538000.0,3,2.25,2570.0,7242.0,2.0,No,NaN,...,7,2170.0,400,67,1991,98125.0,47.7210,-122.319,1690.0,7639
2,5631500400,15 February 2016,180000.0,2,1.00,770.0,10000.0,1.0,No,NaN,...,6,770.0,0,85,0,98028.0,47.7379,-122.233,2720.0,8062
3,2487200875,14 December 2017,604000.0,4,3.00,1960.0,5000.0,1.0,No,NaN,...,7,1050.0,910,53,0,98136.0,47.5208,-122.393,1360.0,5000
4,1954400510,15 February 2016,510000.0,3,2.00,1680.0,8080.0,1.0,No,NaN,...,8,1680.0,0,31,0,98074.0,47.6168,-122.045,1800.0,7503
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,263000018,14 May 2017,360000.0,3,2.50,1530.0,1131.0,3.0,No,NaN,...,8,1530.0,0,9,0,98103.0,47.6993,-122.346,1530.0,1509
21609,6600060120,15 February 2016,400000.0,4,2.50,2310.0,5813.0,2.0,No,NaN,...,8,2310.0,0,4,0,98146.0,47.5107,-122.362,1830.0,7200
21610,1523300141,14 June 2017,402101.0,2,0.75,1020.0,1350.0,2.0,No,NaN,...,7,1020.0,0,9,0,98144.0,47.5944,-122.299,1020.0,2007
21611,291310100,15 January 2016,400000.0,3,2.50,1600.0,2388.0,2.0,No,NaN,...,8,1600.0,0,14,0,98027.0,47.5345,-122.069,1410.0,1287
21612,1523300157,14 October 2017,325000.0,2,0.75,1020.0,1076.0,2.0,No,NaN,...,7,1020.0,0,10,0,98144.0,47.5941,-122.299,1020.0,1357

In [146]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21613 entries, 0 to 21612
Data columns (total 21 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   ID                                         21613 non-null  int64
 1   Date House was Sold                        21613 non-null  object
 2   Sale Price                                 21609 non-null  float64
 3   No of Bedrooms                             21613 non-null  int64
 4   No of Bathrooms                            21609 non-null  float64
 5   Flat Area (in Sqft)                        21604 non-null  float64
 6   Lot Area (in Sqft)                         21604 non-null  float64
 7   No of Floors                               21613 non-null  float64
 8   Waterfront View                            21613 non-null  object
 9   No of Times Visited                        2124 non-null   object
 10  Condition of the House                     21613 non-null  object
 11  Overall Grade                              21613 non-null  int64
 12  Area of the House from Basement (in Sqft)  21610 non-null  float64
 13  Basement Area (in Sqft)                    21613 non-null  int64
 14  Age of House (in Years)                    21613 non-null  int64
 15  Renovated Year                             21613 non-null  int64
 16  Zipcode                                    21612 non-null  float64
 17  Latitude                                   21612 non-null  float64
 18  Longitude                                  21612 non-null  float64
 19  Living Area after Renovation (in Sqft)     21612 non-null  float64
 20  Lot Area after Renovation (in Sqft)        21613 non-null  int64
dtypes: float64(10), int64(7), object(4)
memory usage: 3.5+ MB

In [147]:
df.describe()

,ID,Sale Price,No of Bedrooms,No of Bathrooms,Flat Area (in Sqft),Lot Area (in Sqft),No of Floors,Overall Grade,Area of the House from Basement (in Sqft),Basement Area (in Sqft),Age of House (in Years),Renovated Year,Zipcode,Latitude,Longitude,Living Area after Renovation (in Sqft),Lot Area after Renovation (in Sqft)
count,2.161300e+04,2.160900e+04,21613.000000,21609.000000,21604.000000,2.160400e+04,21613.000000,21613.000000,21610.000000,21613.000000,21613.000000,21613.000000,21612.000000,21612.000000,21612.000000,21612.000000,21613.000000
mean,4.580302e+09,5.401984e+05,3.370842,2.114732,2079.931772,1.510776e+04,1.494309,7.623467,1788.344193,291.509045,46.994864,84.402258,98077.937766,47.560048,-122.213892,1986.538914,12768.455652
std,2.876566e+09,3.673890e+05,0.930062,0.770138,918.487597,4.142827e+04,0.539989,1.105439,827.982604,442.575043,29.373411,401.679240,53.505425,0.138565,0.140830,685.404255,27304.179631
min,1.000102e+06,7.500000e+04,0.000000,0.000000,290.000000,5.200000e+02,1.000000,1.000000,290.000000,0.000000,3.000000,0.000000,98001.000000,47.155900,-122.519000,399.000000,651.000000
25%,2.123049e+09,3.219500e+05,3.000000,1.750000,1429.250000,5.040000e+03,1.000000,7.000000,1190.000000,0.000000,21.000000,0.000000,98033.000000,47.470975,-122.328000,1490.000000,5100.000000
50%,3.904930e+09,4.500000e+05,3.000000,2.250000,1910.000000,7.617500e+03,1.500000,7.000000,1560.000000,0.000000,43.000000,0.000000,98065.000000,47.571800,-122.230000,1840.000000,7620.000000
75%,7.308900e+09,6.450000e+05,4.000000,2.500000,2550.000000,1.068825e+04,2.000000,8.000000,2210.000000,560.000000,67.000000,0.000000,98118.000000,47.678000,-122.125000,2360.000000,10083.000000
max,9.900000e+09,7.700000e+06,33.000000,8.000000,13540.000000,1.651359e+06,3.500000,10.000000,9410.000000,4820.000000,118.000000,2015.000000,98199.000000,47.777600,-121.315000,6210.000000,871200.000000

In [148]:
df.isnull().sum()

ID                                               0
Date House was Sold                              0
Sale Price                                       4
No of Bedrooms                                   0
No of Bathrooms                                  4
Flat Area (in Sqft)                              9
Lot Area (in Sqft)                               9
No of Floors                                     0
Waterfront View                                  0
No of Times Visited                          19489
Condition of the House                           0
Overall Grade                                    0
Area of the House from Basement (in Sqft)        3
Basement Area (in Sqft)                          0
Age of House (in Years)                          0
Renovated Year                                   0
Zipcode                                          1
Latitude                                         1
Longitude                                        1
Living Area after Renovation (in Sqft)           1
Lot Area after Renovation (in Sqft)              0
dtype: int64

In [149]:
df.isnull().mean() * 100

ID                                            0.000000
Date House was Sold                           0.000000
Sale Price                                    0.018507
No of Bedrooms                                0.000000
No of Bathrooms                               0.018507
Flat Area (in Sqft)                           0.041642
Lot Area (in Sqft)                            0.041642
No of Floors                                  0.000000
Waterfront View                               0.000000
No of Times Visited                          90.172581
Condition of the House                        0.000000
Overall Grade                                 0.000000
Area of the House from Basement (in Sqft)     0.013881
Basement Area (in Sqft)                       0.000000
Age of House (in Years)                       0.000000
Renovated Year                                0.000000
Zipcode                                       0.004627
Latitude                                      0.004627
Longitude                                     0.004627
Living Area after Renovation (in Sqft)        0.004627
Lot Area after Renovation (in Sqft)           0.000000
dtype: float64

In [150]:
df.duplicated().sum()

np.int64(0)

In [151]:

df_cleaned_rows = df.drop_duplicates()


#df = df.T.drop_duplicates().T


df_cleaned_rows

,ID,Date House was Sold,Sale Price,No of Bedrooms,No of Bathrooms,Flat Area (in Sqft),Lot Area (in Sqft),No of Floors,Waterfront View,No of Times Visited,...,Overall Grade,Area of the House from Basement (in Sqft),Basement Area (in Sqft),Age of House (in Years),Renovated Year,Zipcode,Latitude,Longitude,Living Area after Renovation (in Sqft),Lot Area after Renovation (in Sqft)
0,7129300520,14 October 2017,221900.0,3,1.00,1180.0,5650.0,1.0,No,NaN,...,7,1180.0,0,63,0,98178.0,47.5112,-122.257,1340.0,5650
1,6414100192,14 December 2017,538000.0,3,2.25,2570.0,7242.0,2.0,No,NaN,...,7,2170.0,400,67,1991,98125.0,47.7210,-122.319,1690.0,7639
2,5631500400,15 February 2016,180000.0,2,1.00,770.0,10000.0,1.0,No,NaN,...,6,770.0,0,85,0,98028.0,47.7379,-122.233,2720.0,8062
3,2487200875,14 December 2017,604000.0,4,3.00,1960.0,5000.0,1.0,No,NaN,...,7,1050.0,910,53,0,98136.0,47.5208,-122.393,1360.0,5000
4,1954400510,15 February 2016,510000.0,3,2.00,1680.0,8080.0,1.0,No,NaN,...,8,1680.0,0,31,0,98074.0,47.6168,-122.045,1800.0,7503
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,263000018,14 May 2017,360000.0,3,2.50,1530.0,1131.0,3.0,No,NaN,...,8,1530.0,0,9,0,98103.0,47.6993,-122.346,1530.0,1509
21609,6600060120,15 February 2016,400000.0,4,2.50,2310.0,5813.0,2.0,No,NaN,...,8,2310.0,0,4,0,98146.0,47.5107,-122.362,1830.0,7200
21610,1523300141,14 June 2017,402101.0,2,0.75,1020.0,1350.0,2.0,No,NaN,...,7,1020.0,0,9,0,98144.0,47.5944,-122.299,1020.0,2007
21611,291310100,15 January 2016,400000.0,3,2.50,1600.0,2388.0,2.0,No,NaN,...,8,1600.0,0,14,0,98027.0,47.5345,-122.069,1410.0,1287
21612,1523300157,14 October 2017,325000.0,2,0.75,1020.0,1076.0,2.0,No,NaN,...,7,1020.0,0,10,0,98144.0,47.5941,-122.299,1020.0,1357

In [152]:
df_clean = df_cleaned_rows.T.drop_duplicates().T
df_clean

,ID,Date House was Sold,Sale Price,No of Bedrooms,No of Bathrooms,Flat Area (in Sqft),Lot Area (in Sqft),No of Floors,Waterfront View,No of Times Visited,...,Overall Grade,Area of the House from Basement (in Sqft),Basement Area (in Sqft),Age of House (in Years),Renovated Year,Zipcode,Latitude,Longitude,Living Area after Renovation (in Sqft),Lot Area after Renovation (in Sqft)
0,7129300520,14 October 2017,221900.0,3,1.0,1180.0,5650.0,1.0,No,NaN,...,7,1180.0,0,63,0,98178.0,47.5112,-122.257,1340.0,5650
1,6414100192,14 December 2017,538000.0,3,2.25,2570.0,7242.0,2.0,No,NaN,...,7,2170.0,400,67,1991,98125.0,47.721,-122.319,1690.0,7639
2,5631500400,15 February 2016,180000.0,2,1.0,770.0,10000.0,1.0,No,NaN,...,6,770.0,0,85,0,98028.0,47.7379,-122.233,2720.0,8062
3,2487200875,14 December 2017,604000.0,4,3.0,1960.0,5000.0,1.0,No,NaN,...,7,1050.0,910,53,0,98136.0,47.5208,-122.393,1360.0,5000
4,1954400510,15 February 2016,510000.0,3,2.0,1680.0,8080.0,1.0,No,NaN,...,8,1680.0,0,31,0,98074.0,47.6168,-122.045,1800.0,7503
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,263000018,14 May 2017,360000.0,3,2.5,1530.0,1131.0,3.0,No,NaN,...,8,1530.0,0,9,0,98103.0,47.6993,-122.346,1530.0,1509
21609,6600060120,15 February 2016,400000.0,4,2.5,2310.0,5813.0,2.0,No,NaN,...,8,2310.0,0,4,0,98146.0,47.5107,-122.362,1830.0,7200
21610,1523300141,14 June 2017,402101.0,2,0.75,1020.0,1350.0,2.0,No,NaN,...,7,1020.0,0,9,0,98144.0,47.5944,-122.299,1020.0,2007
21611,291310100,15 January 2016,400000.0,3,2.5,1600.0,2388.0,2.0,No,NaN,...,8,1600.0,0,14,0,98027.0,47.5345,-122.069,1410.0,1287
21612,1523300157,14 October 2017,325000.0,2,0.75,1020.0,1076.0,2.0,No,NaN,...,7,1020.0,0,10,0,98144.0,47.5941,-122.299,1020.0,1357

In [153]:
df_clean.isnull().sum()

ID                                               0
Date House was Sold                              0
Sale Price                                       4
No of Bedrooms                                   0
No of Bathrooms                                  4
Flat Area (in Sqft)                              9
Lot Area (in Sqft)                               9
No of Floors                                     0
Waterfront View                                  0
No of Times Visited                          19489
Condition of the House                           0
Overall Grade                                    0
Area of the House from Basement (in Sqft)        3
Basement Area (in Sqft)                          0
Age of House (in Years)                          0
Renovated Year                                   0
Zipcode                                          1
Latitude                                         1
Longitude                                        1
Living Area after Renovation (in Sqft)           1
Lot Area after Renovation (in Sqft)              0
dtype: int64

In [154]:
num_cols_median = [
    'Sale Price', 'No of Bathrooms', 'Flat Area (in Sqft)', 'Lot Area (in Sqft)',
    'Area of the House from Basement (in Sqft)', 'Living Area after Renovation (in Sqft)'
]
for col in num_cols_median:
    df_clean[col] = df_clean[col].fillna(df_clean[col].median())

geo_cols = ['Zipcode', 'Latitude', 'Longitude']
for col in geo_cols:
    df_clean[col] = df_clean[col].fillna(df_clean[col].mode()[0])

df_clean['No of Times Visited'] = df_clean['No of Times Visited'].fillna(df_clean['No of Times Visited'].mode()[0])

print("Remaining missing values:")
print(df_clean.isnull().sum())


df_clean

Remaining missing values:
ID                                           0
Date House was Sold                          0
Sale Price                                   0
No of Bedrooms                               0
No of Bathrooms                              0
Flat Area (in Sqft)                          0
Lot Area (in Sqft)                           0
No of Floors                                 0
Waterfront View                              0
No of Times Visited                          0
Condition of the House                       0
Overall Grade                                0
Area of the House from Basement (in Sqft)    0
Basement Area (in Sqft)                      0
Age of House (in Years)                      0
Renovated Year                               0
Zipcode                                      0
Latitude                                     0
Longitude                                    0
Living Area after Renovation (in Sqft)       0
Lot Area after Renovation (in Sqft)          0
dtype: int64

/tmp/ipykernel_2061/4284335356.py:6: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_clean[col] = df_clean[col].fillna(df_clean[col].median())
/tmp/ipykernel_2061/4284335356.py:6: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_clean[col] = df_clean[col].fillna(df_clean[col].median())
/tmp/ipykernel_2061/4284335356.py:6: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_clean[col] = df_clean[col].fillna(df_clean[col].median())
/tmp/ipykernel_2061/4284335356.py:6: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_clean[col] = df_clean[col].fillna(df_clean[col].median())
/tmp/ipykernel_2061/4284335356.py:6: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_clean[col] = df_clean[col].fillna(df_clean[col].median())
/tmp/ipykernel_2061/4284335356.py:6: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_clean[col] = df_clean[col].fillna(df_clean[col].median())
/tmp/ipykernel_2061/4284335356.py:10: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_clean[col] = df_clean[col].fillna(df_clean[col].mode()[0])

,ID,Date House was Sold,Sale Price,No of Bedrooms,No of Bathrooms,Flat Area (in Sqft),Lot Area (in Sqft),No of Floors,Waterfront View,No of Times Visited,...,Overall Grade,Area of the House from Basement (in Sqft),Basement Area (in Sqft),Age of House (in Years),Renovated Year,Zipcode,Latitude,Longitude,Living Area after Renovation (in Sqft),Lot Area after Renovation (in Sqft)
0,7129300520,14 October 2017,221900.0,3,1.00,1180.0,5650.0,1.0,No,Twice,...,7,1180.0,0,63,0,98178.0,47.5112,-122.257,1340.0,5650
1,6414100192,14 December 2017,538000.0,3,2.25,2570.0,7242.0,2.0,No,Twice,...,7,2170.0,400,67,1991,98125.0,47.7210,-122.319,1690.0,7639
2,5631500400,15 February 2016,180000.0,2,1.00,770.0,10000.0,1.0,No,Twice,...,6,770.0,0,85,0,98028.0,47.7379,-122.233,2720.0,8062
3,2487200875,14 December 2017,604000.0,4,3.00,1960.0,5000.0,1.0,No,Twice,...,7,1050.0,910,53,0,98136.0,47.5208,-122.393,1360.0,5000
4,1954400510,15 February 2016,510000.0,3,2.00,1680.0,8080.0,1.0,No,Twice,...,8,1680.0,0,31,0,98074.0,47.6168,-122.045,1800.0,7503
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,263000018,14 May 2017,360000.0,3,2.50,1530.0,1131.0,3.0,No,Twice,...,8,1530.0,0,9,0,98103.0,47.6993,-122.346,1530.0,1509
21609,6600060120,15 February 2016,400000.0,4,2.50,2310.0,5813.0,2.0,No,Twice,...,8,2310.0,0,4,0,98146.0,47.5107,-122.362,1830.0,7200
21610,1523300141,14 June 2017,402101.0,2,0.75,1020.0,1350.0,2.0,No,Twice,...,7,1020.0,0,9,0,98144.0,47.5944,-122.299,1020.0,2007
21611,291310100,15 January 2016,400000.0,3,2.50,1600.0,2388.0,2.0,No,Twice,...,8,1600.0,0,14,0,98027.0,47.5345,-122.069,1410.0,1287
21612,1523300157,14 October 2017,325000.0,2,0.75,1020.0,1076.0,2.0,No,Twice,...,7,1020.0,0,10,0,98144.0,47.5941,-122.299,1020.0,1357

In [155]:
from sklearn.preprocessing import StandardScaler

df_scaled = df_clean.copy()

exclude_cols = ['Sale Price', 'ID', 'Date House was Sold', 'Waterfront View', 'No of Times Visited', 'Condition of the House']
num_cols = [col for col in df_scaled.columns if col not in exclude_cols]

scaler = StandardScaler()

df_scaled[num_cols] = scaler.fit_transform(df_scaled[num_cols].astype(float))

df_scaled

,ID,Date House was Sold,Sale Price,No of Bedrooms,No of Bathrooms,Flat Area (in Sqft),Lot Area (in Sqft),No of Floors,Waterfront View,No of Times Visited,...,Overall Grade,Area of the House from Basement (in Sqft),Basement Area (in Sqft),Age of House (in Years),Renovated Year,Zipcode,Latitude,Longitude,Living Area after Renovation (in Sqft),Lot Area after Renovation (in Sqft)
0,7129300520,14 October 2017,221900.0,-0.398737,-1.447640,-0.979940,-0.228268,-0.915427,No,Twice,...,-0.564013,-0.734756,-0.658681,0.544898,-0.210128,1.870188,-0.352531,-0.306090,-0.943328,-0.260715
1,6414100192,14 December 2017,538000.0,-0.398737,0.175628,0.533757,-0.189832,0.936506,No,Twice,...,-0.564013,0.461025,0.245141,0.681079,4.746678,0.879593,1.161628,-0.746356,-0.432658,-0.187868
2,5631500400,15 February 2016,180000.0,-1.473959,-1.447640,-1.426426,-0.123244,-0.915427,No,Twice,...,-1.468651,-1.229979,-0.658681,1.293892,-0.210128,-0.933382,1.283598,-0.135665,1.070173,-0.172375
3,2487200875,14 December 2017,604000.0,0.676485,1.149589,-0.130528,-0.243962,-0.915427,No,Twice,...,-0.564013,-0.891778,1.397515,0.204446,-0.210128,1.085188,-0.283247,-1.271833,-0.914147,-0.284522
4,1954400510,15 February 2016,510000.0,-0.398737,-0.149026,-0.435445,-0.169600,-0.915427,No,Twice,...,0.340626,-0.130826,-0.658681,-0.544548,-0.210128,-0.073620,0.409600,1.199332,-0.272161,-0.192849
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,263000018,14 May 2017,360000.0,-0.398737,0.500282,-0.598793,-0.337373,2.788439,No,Twice,...,0.340626,-0.312005,-0.658681,-1.293542,-0.210128,0.468403,1.005015,-0.938084,-0.666107,-0.412381
21609,6600060120,15 February 2016,400000.0,0.676485,0.500282,0.250619,-0.224333,0.936506,No,Twice,...,0.340626,0.630126,-0.658681,-1.463768,-0.210128,1.272093,-0.356140,-1.051701,-0.228390,-0.203946
21610,1523300141,14 June 2017,402101.0,-1.473959,-1.772294,-1.154179,-0.332086,0.936506,No,Twice,...,-0.564013,-0.928014,-0.658681,-1.293542,-0.210128,1.234712,0.247936,-0.604335,-1.410227,-0.394141
21611,291310100,15 January 2016,400000.0,-0.398737,0.500282,-0.522564,-0.307025,0.936506,No,Twice,...,0.340626,-0.227455,-0.658681,-1.123316,-0.210128,-0.952072,-0.184372,1.028907,-0.841194,-0.420511
21612,1523300157,14 October 2017,325000.0,-1.473959,-1.772294,-1.154179,-0.338701,0.936506,No,Twice,...,-0.564013,-0.928014,-0.658681,-1.259497,-0.210128,1.234712,0.245771,-0.604335,-1.410227,-0.417948

In [156]:
from sklearn.preprocessing import LabelEncoder,OrdinalEncoder

In [157]:
df_clean.select_dtypes(include=['object', 'category']).columns.tolist()

['ID',
 'Date House was Sold',
 'No of Bedrooms',
 'No of Floors',
 'Waterfront View',
 'No of Times Visited',
 'Condition of the House',
 'Overall Grade',
 'Basement Area (in Sqft)',
 'Age of House (in Years)',
 'Renovated Year',
 'Lot Area after Renovation (in Sqft)']

In [158]:
condition_map = {'Bad': 0, 'Fair': 1, 'Good': 2, 'Excellent': 3}
visit_map = {'None': 0, 'Once': 1, 'Twice': 2, 'Thrice': 3, 'Four': 4}
label_enc = LabelEncoder()
df_clean['Condition of the House'] = label_enc.fit_transform(df_clean['Condition of the House'])
df_clean['No of Times Visited'] = label_enc.fit_transform(df_clean['No of Times Visited'])
df_clean

,ID,Date House was Sold,Sale Price,No of Bedrooms,No of Bathrooms,Flat Area (in Sqft),Lot Area (in Sqft),No of Floors,Waterfront View,No of Times Visited,...,Overall Grade,Area of the House from Basement (in Sqft),Basement Area (in Sqft),Age of House (in Years),Renovated Year,Zipcode,Latitude,Longitude,Living Area after Renovation (in Sqft),Lot Area after Renovation (in Sqft)
0,7129300520,14 October 2017,221900.0,3,1.00,1180.0,5650.0,1.0,No,3,...,7,1180.0,0,63,0,98178.0,47.5112,-122.257,1340.0,5650
1,6414100192,14 December 2017,538000.0,3,2.25,2570.0,7242.0,2.0,No,3,...,7,2170.0,400,67,1991,98125.0,47.7210,-122.319,1690.0,7639
2,5631500400,15 February 2016,180000.0,2,1.00,770.0,10000.0,1.0,No,3,...,6,770.0,0,85,0,98028.0,47.7379,-122.233,2720.0,8062
3,2487200875,14 December 2017,604000.0,4,3.00,1960.0,5000.0,1.0,No,3,...,7,1050.0,910,53,0,98136.0,47.5208,-122.393,1360.0,5000
4,1954400510,15 February 2016,510000.0,3,2.00,1680.0,8080.0,1.0,No,3,...,8,1680.0,0,31,0,98074.0,47.6168,-122.045,1800.0,7503
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,263000018,14 May 2017,360000.0,3,2.50,1530.0,1131.0,3.0,No,3,...,8,1530.0,0,9,0,98103.0,47.6993,-122.346,1530.0,1509
21609,6600060120,15 February 2016,400000.0,4,2.50,2310.0,5813.0,2.0,No,3,...,8,2310.0,0,4,0,98146.0,47.5107,-122.362,1830.0,7200
21610,1523300141,14 June 2017,402101.0,2,0.75,1020.0,1350.0,2.0,No,3,...,7,1020.0,0,9,0,98144.0,47.5944,-122.299,1020.0,2007
21611,291310100,15 January 2016,400000.0,3,2.50,1600.0,2388.0,2.0,No,3,...,8,1600.0,0,14,0,98027.0,47.5345,-122.069,1410.0,1287
21612,1523300157,14 October 2017,325000.0,2,0.75,1020.0,1076.0,2.0,No,3,...,7,1020.0,0,10,0,98144.0,47.5941,-122.299,1020.0,1357

In [159]:
from sklearn.preprocessing import OneHotEncoder

onehot_enc = OneHotEncoder(drop='first', sparse_output=False, dtype=int)

encoded_array = onehot_enc.fit_transform(df_clean[['Waterfront View']])

encoded_col_name = onehot_enc.get_feature_names_out(['Waterfront View'])
df_clean[encoded_col_name] = encoded_array

df_clean.drop(columns=['Waterfront View'], inplace=True)

df_clean

,ID,Date House was Sold,Sale Price,No of Bedrooms,No of Bathrooms,Flat Area (in Sqft),Lot Area (in Sqft),No of Floors,No of Times Visited,Condition of the House,...,Area of the House from Basement (in Sqft),Basement Area (in Sqft),Age of House (in Years),Renovated Year,Zipcode,Latitude,Longitude,Living Area after Renovation (in Sqft),Lot Area after Renovation (in Sqft),Waterfront View_Yes
0,7129300520,14 October 2017,221900.0,3,1.00,1180.0,5650.0,1.0,3,2,...,1180.0,0,63,0,98178.0,47.5112,-122.257,1340.0,5650,0
1,6414100192,14 December 2017,538000.0,3,2.25,2570.0,7242.0,2.0,3,2,...,2170.0,400,67,1991,98125.0,47.7210,-122.319,1690.0,7639,0
2,5631500400,15 February 2016,180000.0,2,1.00,770.0,10000.0,1.0,3,2,...,770.0,0,85,0,98028.0,47.7379,-122.233,2720.0,8062,0
3,2487200875,14 December 2017,604000.0,4,3.00,1960.0,5000.0,1.0,3,1,...,1050.0,910,53,0,98136.0,47.5208,-122.393,1360.0,5000,0
4,1954400510,15 February 2016,510000.0,3,2.00,1680.0,8080.0,1.0,3,2,...,1680.0,0,31,0,98074.0,47.6168,-122.045,1800.0,7503,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,263000018,14 May 2017,360000.0,3,2.50,1530.0,1131.0,3.0,3,2,...,1530.0,0,9,0,98103.0,47.6993,-122.346,1530.0,1509,0
21609,6600060120,15 February 2016,400000.0,4,2.50,2310.0,5813.0,2.0,3,2,...,2310.0,0,4,0,98146.0,47.5107,-122.362,1830.0,7200,0
21610,1523300141,14 June 2017,402101.0,2,0.75,1020.0,1350.0,2.0,3,2,...,1020.0,0,9,0,98144.0,47.5944,-122.299,1020.0,2007,0
21611,291310100,15 January 2016,400000.0,3,2.50,1600.0,2388.0,2.0,3,2,...,1600.0,0,14,0,98027.0,47.5345,-122.069,1410.0,1287,0
21612,1523300157,14 October 2017,325000.0,2,0.75,1020.0,1076.0,2.0,3,2,...,1020.0,0,10,0,98144.0,47.5941,-122.299,1020.0,1357,0

In [160]:
outlier_features = [
    'Sale Price',
    'Flat Area (in Sqft)',
    'Lot Area (in Sqft)',
    'Area of the House from Basement (in Sqft)'
]

for col in outlier_features:
    Q1 = df_clean[col].quantile(0.25)
    Q3 = df_clean[col].quantile(0.75)
    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outliers_count = ((df_clean[col] < lower_bound) | (df_clean[col] > upper_bound)).sum()
    print(f"Feature '{col}': Removing {outliers_count} outlier rows.")

    df_clean = df_clean[(df_clean[col] >= lower_bound) & (df_clean[col] <= upper_bound)]

df_clean

Feature 'Sale Price': Removing 1159 outlier rows.
Feature 'Flat Area (in Sqft)': Removing 319 outlier rows.
Feature 'Lot Area (in Sqft)': Removing 2112 outlier rows.
Feature 'Area of the House from Basement (in Sqft)': Removing 466 outlier rows.

,ID,Date House was Sold,Sale Price,No of Bedrooms,No of Bathrooms,Flat Area (in Sqft),Lot Area (in Sqft),No of Floors,No of Times Visited,Condition of the House,...,Area of the House from Basement (in Sqft),Basement Area (in Sqft),Age of House (in Years),Renovated Year,Zipcode,Latitude,Longitude,Living Area after Renovation (in Sqft),Lot Area after Renovation (in Sqft),Waterfront View_Yes
0,7129300520,14 October 2017,221900.0,3,1.00,1180.0,5650.0,1.0,3,2,...,1180.0,0,63,0,98178.0,47.5112,-122.257,1340.0,5650,0
1,6414100192,14 December 2017,538000.0,3,2.25,2570.0,7242.0,2.0,3,2,...,2170.0,400,67,1991,98125.0,47.7210,-122.319,1690.0,7639,0
2,5631500400,15 February 2016,180000.0,2,1.00,770.0,10000.0,1.0,3,2,...,770.0,0,85,0,98028.0,47.7379,-122.233,2720.0,8062,0
3,2487200875,14 December 2017,604000.0,4,3.00,1960.0,5000.0,1.0,3,1,...,1050.0,910,53,0,98136.0,47.5208,-122.393,1360.0,5000,0
4,1954400510,15 February 2016,510000.0,3,2.00,1680.0,8080.0,1.0,3,2,...,1680.0,0,31,0,98074.0,47.6168,-122.045,1800.0,7503,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,263000018,14 May 2017,360000.0,3,2.50,1530.0,1131.0,3.0,3,2,...,1530.0,0,9,0,98103.0,47.6993,-122.346,1530.0,1509,0
21609,6600060120,15 February 2016,400000.0,4,2.50,2310.0,5813.0,2.0,3,2,...,2310.0,0,4,0,98146.0,47.5107,-122.362,1830.0,7200,0
21610,1523300141,14 June 2017,402101.0,2,0.75,1020.0,1350.0,2.0,3,2,...,1020.0,0,9,0,98144.0,47.5944,-122.299,1020.0,2007,0
21611,291310100,15 January 2016,400000.0,3,2.50,1600.0,2388.0,2.0,3,2,...,1600.0,0,14,0,98027.0,47.5345,-122.069,1410.0,1287,0
21612,1523300157,14 October 2017,325000.0,2,0.75,1020.0,1076.0,2.0,3,2,...,1020.0,0,10,0,98144.0,47.5941,-122.299,1020.0,1357,0

In [161]:
from sklearn.model_selection import train_test_split


X = df_clean.drop(columns=['Sale Price'])
y = df_clean['Sale Price']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [162]:
print(f"Shape of X (features): {X.shape}")
print(f"Shape of y (target): {y.shape}")

Shape of X (features): (17557, 20)
Shape of y (target): (17557,)

In [163]:
X_train.shape

(14045, 20)

In [164]:
y_train.shape

(14045,)

In [165]:
X_test.shape

(3512, 20)

In [166]:
y_test.shape

(3512,)

In [167]:
#removing reduntant columns
df_clean.drop(columns=['ID', 'Date House was Sold', 'Waterfront View'], errors='ignore', inplace=True)
df_clean

,Sale Price,No of Bedrooms,No of Bathrooms,Flat Area (in Sqft),Lot Area (in Sqft),No of Floors,No of Times Visited,Condition of the House,Overall Grade,Area of the House from Basement (in Sqft),Basement Area (in Sqft),Age of House (in Years),Renovated Year,Zipcode,Latitude,Longitude,Living Area after Renovation (in Sqft),Lot Area after Renovation (in Sqft),Waterfront View_Yes
0,221900.0,3,1.00,1180.0,5650.0,1.0,3,2,7,1180.0,0,63,0,98178.0,47.5112,-122.257,1340.0,5650,0
1,538000.0,3,2.25,2570.0,7242.0,2.0,3,2,7,2170.0,400,67,1991,98125.0,47.7210,-122.319,1690.0,7639,0
2,180000.0,2,1.00,770.0,10000.0,1.0,3,2,6,770.0,0,85,0,98028.0,47.7379,-122.233,2720.0,8062,0
3,604000.0,4,3.00,1960.0,5000.0,1.0,3,1,7,1050.0,910,53,0,98136.0,47.5208,-122.393,1360.0,5000,0
4,510000.0,3,2.00,1680.0,8080.0,1.0,3,2,8,1680.0,0,31,0,98074.0,47.6168,-122.045,1800.0,7503,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,360000.0,3,2.50,1530.0,1131.0,3.0,3,2,8,1530.0,0,9,0,98103.0,47.6993,-122.346,1530.0,1509,0
21609,400000.0,4,2.50,2310.0,5813.0,2.0,3,2,8,2310.0,0,4,0,98146.0,47.5107,-122.362,1830.0,7200,0
21610,402101.0,2,0.75,1020.0,1350.0,2.0,3,2,7,1020.0,0,9,0,98144.0,47.5944,-122.299,1020.0,2007,0
21611,400000.0,3,2.50,1600.0,2388.0,2.0,3,2,8,1600.0,0,14,0,98027.0,47.5345,-122.069,1410.0,1287,0
21612,325000.0,2,0.75,1020.0,1076.0,2.0,3,2,7,1020.0,0,10,0,98144.0,47.5941,-122.299,1020.0,1357,0